hostname bgpd-rr400
password zebra
!
router bgp 400
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 neighbor 10.40.0.2 remote-as 400
 neighbor 10.40.0.3 remote-as 400
 neighbor 2001:db8:40::2 remote-as 400
 neighbor 2001:db8:40::3 remote-as 400
 neighbor 2001:db8:40::2 update-source 2001:db8:40::1
 neighbor 2001:db8:40::3 update-source 2001:db8:40::1
 !
 address-family ipv4 unicast
  neighbor 10.40.0.2 activate
  neighbor 10.40.0.2 route-reflector-client
  neighbor 10.40.0.3 activate
  neighbor 10.40.0.3 route-reflector-client
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8:40::2 activate
  neighbor 2001:db8:40::2 route-reflector-client
  neighbor 2001:db8:40::3 activate
  neighbor 2001:db8:40::3 route-reflector-client
 exit-address-family
!
line vty
