hostname bgpd-r401
password zebra
!
router bgp 400
 bgp router-id 4.4.4.1
 no bgp ebgp-requires-policy
 neighbor 10.40.0.1 remote-as 400
 neighbor 172.16.24.1 remote-as 200
 neighbor 2001:db8:40::1 remote-as 400
 neighbor 2001:db8:24::1 remote-as 200
 neighbor 2001:db8:40::1 update-source 2001:db8:40::2
 neighbor 2001:db8:24::1 update-source 2001:db8:24::2
 !
 address-family ipv4 unicast
  network 10.40.1.0/24
  neighbor 10.40.0.1 activate
  neighbor 10.40.0.1 next-hop-self
  neighbor 172.16.24.1 activate
 exit-address-family
 !
 address-family ipv6 unicast
  network 2001:db8:401::/64
  neighbor 2001:db8:40::1 activate
  neighbor 2001:db8:40::1 next-hop-self
  neighbor 2001:db8:24::1 activate
 exit-address-family
!
line vty
